services:
  worker:
    build:
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - ./envs/worker.env
  api:
    build:
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    env_file:
      - ./envs/api.env
    depends_on:
      - redis
      - postgres
  client:
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - api
  nginx:
    build:
      context: ./nginx
    ports:
      - 8080:80
    depends_on:
      - api
      - client
