services:
  worker:
    image: kodega2016/fib-worker
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  api:
    image: kodega2016/fib-api
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  client:
    mem_limit: 128m
    image: kodega2016/fib-client
  nginx:
    image: kodega2016/fib-nginx
    mem_limit: 128m
    ports:
      - 80:80
